package tui

import (
	"fmt"
	"strconv"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/shiva/gonix/internal/certificates"
	"github.com/shiva/gonix/internal/nginx"
)

// hostDetailScreen implements the per-host management submenu described in
// the project specification (section 6).
type hostDetailScreen struct {
	deps Deps
	host nginx.ListedHost
	menu *simpleMenu
}

const (
	hdToggleEnable = iota
	hdAddPath
	hdAddCustomPath
	hdSSL
	hdWebSocket
	hdProxy
	hdAccessList
	hdLogs
	hdViewConfig
	hdBackupRestore
	hdDelete
)

func newHostDetailScreen(deps Deps, h nginx.ListedHost) *hostDetailScreen {
	s := &hostDetailScreen{deps: deps, host: h}
	s.rebuildMenu()
	return s
}

func (s *hostDetailScreen) rebuildMenu() {
	toggleLabel := "Enable Host"
	if s.host.Enabled {
		toggleLabel = "Disable Host"
	}
	items := []menuItem{
		{title: toggleLabel},
		{title: "Add New Path"},
		{title: "Add Custom Path"},
		{title: "SSL Configuration"},
		{title: "WebSocket Configuration"},
		{title: "Proxy Configuration"},
		{title: "Access List"},
		{title: "Access / Error Logs"},
		{title: "View Configuration"},
		{title: "Backup / Restore"},
		{title: "Delete Host"},
	}
	if !s.host.Managed {
		for i := range items {
			if i == hdToggleEnable || i == hdViewConfig || i == hdDelete || i == hdBackupRestore {
				continue
			}
			items[i].desc = mutedStyle.Render("(unmanaged host)")
		}
	}
	s.menu = newSimpleMenu(items)
}

func (s *hostDetailScreen) Init() tea.Cmd { return nil }

func (s *hostDetailScreen) refreshHost() {
	hostList, err := s.deps.Manager.ListHosts()
	if err != nil {
		return
	}
	for _, h := range hostList {
		if h.FileName == s.host.FileName {
			s.host = h
			return
		}
	}
}

func (s *hostDetailScreen) Update(msg tea.Msg) (screen, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		if s.menu.HandleKey(msg) {
			return s, nil
		}
		switch msg.String() {
		case "esc", "q":
			return s, navPop()
		case "enter":
			return s.dispatch(s.menu.Selected())
		}
	}
	return s, nil
}

func (s *hostDetailScreen) dispatch(choice int) (screen, tea.Cmd) {
	unmanagedBlocked := map[int]bool{
		hdAddPath: true, hdAddCustomPath: true, hdSSL: true,
		hdWebSocket: true, hdProxy: true, hdAccessList: true, hdLogs: true,
	}
	if !s.host.Managed && unmanagedBlocked[choice] {
		return newResultScreen(s.deps, "Unmanaged Host", false,
			"This host's configuration was not generated by GoNix and cannot be edited automatically. Use \"View Configuration\" to inspect it, or edit it manually with a text editor.",
			s), nil
	}

	switch choice {
	case hdToggleEnable:
		return s.toggleEnable()
	case hdViewConfig:
		return s.viewConfig()
	case hdDelete:
		return s.confirmDelete()
	case hdBackupRestore:
		return newBackupScreen(s.deps, s.host), nil
	case hdAddPath:
		return newAddPathWizard(s.deps, s.host), nil
	case hdAddCustomPath:
		return newAddCustomPathWizard(s.deps, s.host), nil
	case hdSSL:
		return newSSLWizard(s.deps, s.host), nil
	case hdWebSocket:
		return s.toggleWebSocket()
	case hdProxy:
		return newProxyWizard(s.deps, s.host), nil
	case hdAccessList:
		return newHostAccessListScreen(s.deps, s.host), nil
	case hdLogs:
		return newLogsWizard(s.deps, s.host), nil
	}
	return s, nil
}

func (s *hostDetailScreen) toggleEnable() (screen, tea.Cmd) {
	ctx := backgroundCtx()
	var err error
	if s.host.Enabled {
		err = s.deps.HostService.DisableHost(ctx, s.host.FileName)
	} else {
		err = s.deps.HostService.EnableHost(ctx, s.host.FileName)
	}
	if err != nil {
		return newResultScreen(s.deps, "Host State", false, err.Error(), s), nil
	}
	s.refreshHost()
	s.rebuildMenu()
	return s, nil
}

func (s *hostDetailScreen) toggleWebSocket() (screen, tea.Cmd) {
	h, err := s.deps.Manager.GetHost(s.host.FileName)
	if err != nil {
		return newResultScreen(s.deps, "WebSocket Configuration", false, err.Error(), s), nil
	}
	for i, loc := range h.Locations {
		if loc.Path == "/" && loc.Proxy != nil {
			h.Locations[i].Proxy.WebSocket = !loc.Proxy.WebSocket
		}
	}
	if _, err := s.deps.HostService.UpdateHost(backgroundCtx(), h); err != nil {
		return newResultScreen(s.deps, "WebSocket Configuration", false, err.Error(), s), nil
	}
	return newResultScreen(s.deps, "WebSocket Configuration", true, "WebSocket setting toggled for location /.", s), nil
}

func (s *hostDetailScreen) viewConfig() (screen, tea.Cmd) {
	content, err := s.deps.Manager.RawConfig(s.host.FileName)
	if err != nil {
		return newResultScreen(s.deps, "View Configuration", false, err.Error(), s), nil
	}
	return newViewerScreen("Configuration: "+s.host.ServerName, content, s), nil
}

func (s *hostDetailScreen) confirmDelete() (screen, tea.Cmd) {
	return newConfirmScreen(
		"Delete Host",
		fmt.Sprintf("Delete host %q? A backup will be kept, but this cannot be undone from the UI.", s.host.ServerName),
		func() (screen, tea.Cmd) {
			if err := s.deps.HostService.DeleteHost(backgroundCtx(), s.host.FileName); err != nil {
				return newResultScreen(s.deps, "Delete Host", false, err.Error(), s), nil
			}
			return newResultScreen(s.deps, "Delete Host", true, "Host deleted.", newHostsListScreen(s.deps)), nil
		},
		func() (screen, tea.Cmd) { return s, nil },
	), nil
}

func (s *hostDetailScreen) View(width, height int) string {
	dot := disabledDot
	state := "DISABLED"
	if s.host.Enabled {
		dot = enabledDot
		state = "ENABLED"
	}
	body := headerStyle.Render("Host: "+s.host.ServerName) + "\n"
	body += dot + " " + state + "\n\n"
	body += s.menu.View()
	help := [][2]string{{"↑↓", "Navigate"}, {"Enter", "Select"}, {"Esc", "Back"}}
	return renderFrame(width, height, "GONIX", body, help)
}

// --- Add New Path ---

func newAddPathWizard(deps Deps, h nginx.ListedHost) *wizardScreen {
	fields := []wizardField{
		{Key: "path", Label: "Location path (e.g. /api/):", Kind: fieldText, Placeholder: "/api/",
			Validate: func(v string) error { return validateLocationPath(v) }},
		{Key: "upstream_host", Label: "Upstream host/IP:", Kind: fieldText, Placeholder: "127.0.0.1", Validate: requireNonEmpty("upstream host")},
		{Key: "upstream_port", Label: "Upstream port:", Kind: fieldText, Placeholder: "8080", Validate: validatePort},
		{Key: "upstream_scheme", Label: "Upstream protocol:", Kind: fieldChoice, Options: []string{"http", "https"}},
		{Key: "websocket", Label: "Enable WebSocket Support?", Kind: fieldBool},
	}
	return newWizard("Add New Path — "+h.ServerName, fields, func(v map[string]string) (screen, tea.Cmd) {
		host, err := deps.Manager.GetHost(h.FileName)
		if err != nil {
			return newResultScreen(deps, "Add New Path", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		port, _ := strconv.Atoi(v["upstream_port"])
		host.Locations = append(host.Locations, nginx.Location{
			Path: v["path"],
			Proxy: &nginx.ProxyConfig{
				UpstreamScheme: v["upstream_scheme"], UpstreamHost: v["upstream_host"], UpstreamPort: port,
				HTTPVersion: "1.1", WebSocket: v["websocket"] == "yes",
				ForwardHost: true, ForwardFor: true, ForwardProto: true, BufferingEnabled: true,
			},
		})
		if _, err := deps.HostService.UpdateHost(backgroundCtx(), host); err != nil {
			return newResultScreen(deps, "Add New Path", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		return newResultScreen(deps, "Add New Path", true, "Location added.", newHostDetailScreen(deps, h)), nil
	}, func() (screen, tea.Cmd) { return newHostDetailScreen(deps, h), nil })
}

func validateLocationPath(p string) error {
	if p == "" || p[0] != '/' {
		return fmt.Errorf("path must start with /")
	}
	return nil
}

// --- Add Custom Path ---

func newAddCustomPathWizard(deps Deps, h nginx.ListedHost) *wizardScreen {
	fields := []wizardField{
		{Key: "path", Label: "Location path (e.g. /custom/):", Kind: fieldText, Placeholder: "/custom/", Validate: validateLocationPath},
		{Key: "config", Label: "Custom location configuration (single line; edit the file later for more):", Kind: fieldText,
			Placeholder: "return 200 'ok';"},
	}
	return newWizard("Add Custom Location — "+h.ServerName, fields, func(v map[string]string) (screen, tea.Cmd) {
		host, err := deps.Manager.GetHost(h.FileName)
		if err != nil {
			return newResultScreen(deps, "Add Custom Location", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		host.Locations = append(host.Locations, nginx.Location{
			Path: v["path"], IsCustom: true, CustomConfig: "        " + v["config"],
		})
		if _, err := deps.HostService.UpdateHost(backgroundCtx(), host); err != nil {
			return newResultScreen(deps, "Add Custom Location", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		return newResultScreen(deps, "Add Custom Location", true,
			"Custom location added. You can edit "+host.ServerName+" directly with a text editor for advanced configuration.",
			newHostDetailScreen(deps, h)), nil
	}, func() (screen, tea.Cmd) { return newHostDetailScreen(deps, h), nil })
}

// --- SSL Configuration ---

func newSSLWizard(deps Deps, h nginx.ListedHost) *wizardScreen {
	certs, _ := certificates.Scan(deps.Config.Certificates.Directory)
	certOptions := make([]string, 0, len(certs))
	for _, c := range certs {
		certOptions = append(certOptions, c.Domain)
	}
	if len(certOptions) == 0 {
		certOptions = []string{h.ServerName}
	}

	fields := []wizardField{
		{Key: "enable", Label: "Enable SSL for this host?", Kind: fieldBool, BoolDefault: h.SSL.Enabled},
		{Key: "cert", Label: "Certificate (from centralized certs directory):", Kind: fieldChoice, Options: certOptions,
			ShowIf: func(v map[string]string) bool { return v["enable"] == "yes" }},
		{Key: "http2", Label: "Enable HTTP/2?", Kind: fieldBool, BoolDefault: true,
			ShowIf: func(v map[string]string) bool { return v["enable"] == "yes" }},
		{Key: "force", Label: "Redirect HTTP to HTTPS?", Kind: fieldBool, BoolDefault: true,
			ShowIf: func(v map[string]string) bool { return v["enable"] == "yes" }},
	}
	return newWizard("SSL Configuration — "+h.ServerName, fields, func(v map[string]string) (screen, tea.Cmd) {
		host, err := deps.Manager.GetHost(h.FileName)
		if err != nil {
			return newResultScreen(deps, "SSL Configuration", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		if v["enable"] == "yes" {
			cert := v["cert"]
			host.SSL = nginx.SSLConfig{
				Enabled:    true,
				CertFile:   deps.Config.Certificates.Directory + "/" + cert + "/fullchain.pem",
				KeyFile:    deps.Config.Certificates.Directory + "/" + cert + "/privkey.pem",
				HTTP2:      v["http2"] == "yes",
				ForceHTTPS: v["force"] == "yes",
			}
			if host.ListenSSL == 0 {
				host.ListenSSL = 443
			}
		} else {
			host.SSL = nginx.SSLConfig{}
		}
		if _, err := deps.HostService.UpdateHost(backgroundCtx(), host); err != nil {
			return newResultScreen(deps, "SSL Configuration", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		return newResultScreen(deps, "SSL Configuration", true, "SSL configuration updated.", newHostDetailScreen(deps, h)), nil
	}, func() (screen, tea.Cmd) { return newHostDetailScreen(deps, h), nil })
}

// --- Proxy Configuration (edits the "/" location) ---

func newProxyWizard(deps Deps, h nginx.ListedHost) *wizardScreen {
	fields := []wizardField{
		{Key: "upstream_host", Label: "Upstream host/IP (for location /):", Kind: fieldText, Validate: requireNonEmpty("upstream host")},
		{Key: "upstream_port", Label: "Upstream port:", Kind: fieldText, Validate: validatePort},
		{Key: "upstream_scheme", Label: "Upstream protocol:", Kind: fieldChoice, Options: []string{"http", "https"}},
		{Key: "connect_timeout", Label: "Connect timeout:", Kind: fieldText, Placeholder: "60s", Default: "60s"},
		{Key: "read_timeout", Label: "Read timeout:", Kind: fieldText, Placeholder: "60s", Default: "60s"},
		{Key: "send_timeout", Label: "Send timeout:", Kind: fieldText, Placeholder: "60s", Default: "60s"},
		{Key: "max_body", Label: "Max request body size (e.g. 10m, empty = default):", Kind: fieldText, Placeholder: "10m"},
	}
	return newWizard("Proxy Configuration — "+h.ServerName, fields, func(v map[string]string) (screen, tea.Cmd) {
		host, err := deps.Manager.GetHost(h.FileName)
		if err != nil {
			return newResultScreen(deps, "Proxy Configuration", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		found := false
		port, _ := strconv.Atoi(v["upstream_port"])
		for i, loc := range host.Locations {
			if loc.Path == "/" && loc.Proxy != nil {
				host.Locations[i].Proxy.UpstreamHost = v["upstream_host"]
				host.Locations[i].Proxy.UpstreamPort = port
				host.Locations[i].Proxy.UpstreamScheme = v["upstream_scheme"]
				host.Locations[i].Proxy.ConnectTimeout = v["connect_timeout"]
				host.Locations[i].Proxy.ReadTimeout = v["read_timeout"]
				host.Locations[i].Proxy.SendTimeout = v["send_timeout"]
				host.Locations[i].Proxy.MaxBodySize = v["max_body"]
				found = true
			}
		}
		if !found {
			return newResultScreen(deps, "Proxy Configuration", false, "host has no location / to configure", newHostDetailScreen(deps, h)), nil
		}
		if _, err := deps.HostService.UpdateHost(backgroundCtx(), host); err != nil {
			return newResultScreen(deps, "Proxy Configuration", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		return newResultScreen(deps, "Proxy Configuration", true, "Proxy configuration updated.", newHostDetailScreen(deps, h)), nil
	}, func() (screen, tea.Cmd) { return newHostDetailScreen(deps, h), nil })
}

// --- Access / Error Logs ---

func newLogsWizard(deps Deps, h nginx.ListedHost) *wizardScreen {
	fields := []wizardField{
		{Key: "access", Label: "Enable Access Log?", Kind: fieldBool, BoolDefault: true},
		{Key: "error", Label: "Enable Error Log?", Kind: fieldBool, BoolDefault: true},
	}
	return newWizard("Access / Error Logs — "+h.ServerName, fields, func(v map[string]string) (screen, tea.Cmd) {
		host, err := deps.Manager.GetHost(h.FileName)
		if err != nil {
			return newResultScreen(deps, "Logs", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		host.AccessLog = v["access"] == "yes"
		host.ErrorLog = v["error"] == "yes"
		if _, err := deps.HostService.UpdateHost(backgroundCtx(), host); err != nil {
			return newResultScreen(deps, "Logs", false, err.Error(), newHostDetailScreen(deps, h)), nil
		}
		return newResultScreen(deps, "Logs", true, "Log settings updated.", newHostDetailScreen(deps, h)), nil
	}, func() (screen, tea.Cmd) { return newHostDetailScreen(deps, h), nil })
}
