package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Manager performs filesystem operations against the Nginx configuration
// directory tree (sites-available / sites-enabled). It is the only layer
// allowed to touch those files directly; the TUI and higher level packages
// must go through it.
type Manager struct {
	SitesAvailable string
	SitesEnabled   string
	Renderer       *Renderer
}

// NewManager builds a Manager rooted at the given sites-available/enabled
// directories.
func NewManager(sitesAvailable, sitesEnabled string, renderer *Renderer) *Manager {
	return &Manager{SitesAvailable: sitesAvailable, SitesEnabled: sitesEnabled, Renderer: renderer}
}

// ListedHost is a Host augmented with filesystem-derived state that is not
// part of the domain model itself.
type ListedHost struct {
	Host
	FileName      string
	BrokenSymlink bool
}

// ListHosts scans SitesAvailable and returns every discovered host, whether
// or not it was generated by GoNix. Enabled state is computed by
// checking for a matching symlink in SitesEnabled.
func (m *Manager) ListHosts() ([]ListedHost, error) {
	entries, err := os.ReadDir(m.SitesAvailable)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading sites-available: %w", err)
	}

	enabled, broken, err := m.enabledLinks()
	if err != nil {
		return nil, err
	}

	var hosts []ListedHost
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		path := filepath.Join(m.SitesAvailable, name)
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		content := string(data)

		var h Host
		if strings.Contains(content, ManagedMarker) {
			h, _ = ParseManagedHost(content)
		} else {
			s := ParseSummary(content)
			h = Host{ServerName: name, Managed: false, SSL: SSLConfig{Enabled: s.SSL}}
			if len(s.ServerNames) > 0 {
				h.ServerName = s.ServerNames[0]
				h.ServerAlias = s.ServerNames[1:]
			}
		}
		h.Enabled = enabled[name]

		hosts = append(hosts, ListedHost{Host: h, FileName: name, BrokenSymlink: broken[name]})
	}

	sort.Slice(hosts, func(i, j int) bool { return hosts[i].FileName < hosts[j].FileName })
	return hosts, nil
}

// enabledLinks reports, per file name in SitesEnabled, whether it is a
// symlink correctly pointing into SitesAvailable, and separately whether it
// is a broken symlink (points to a target that no longer exists).
func (m *Manager) enabledLinks() (enabled map[string]bool, broken map[string]bool, err error) {
	enabled = map[string]bool{}
	broken = map[string]bool{}

	entries, err := os.ReadDir(m.SitesEnabled)
	if err != nil {
		if os.IsNotExist(err) {
			return enabled, broken, nil
		}
		return nil, nil, fmt.Errorf("reading sites-enabled: %w", err)
	}
	for _, e := range entries {
		full := filepath.Join(m.SitesEnabled, e.Name())
		info, statErr := os.Stat(full) // follows symlink
		if statErr != nil {
			broken[e.Name()] = true
			continue
		}
		if info.IsDir() {
			continue
		}
		enabled[e.Name()] = true
	}
	return enabled, broken, nil
}

// GetHost reads and parses a single host by its config file name.
func (m *Manager) GetHost(fileName string) (Host, error) {
	path := filepath.Join(m.SitesAvailable, fileName)
	data, err := os.ReadFile(path)
	if err != nil {
		return Host{}, fmt.Errorf("reading host %s: %w", fileName, err)
	}
	content := string(data)
	if !strings.Contains(content, ManagedMarker) {
		return Host{}, fmt.Errorf("host %s is not managed by GoNix and cannot be parsed for editing", fileName)
	}
	return ParseManagedHost(content)
}

// RawConfig returns the raw configuration file content, used for read-only
// preview of any host regardless of whether it is managed.
func (m *Manager) RawConfig(fileName string) (string, error) {
	data, err := os.ReadFile(filepath.Join(m.SitesAvailable, fileName))
	if err != nil {
		return "", fmt.Errorf("reading host %s: %w", fileName, err)
	}
	return string(data), nil
}

// WriteHost renders h and writes it to sites-available/<ServerName>. It does
// not enable the host or validate the resulting configuration; callers
// should use a higher level workflow (see internal/hosts) for that.
func (m *Manager) WriteHost(h Host) error {
	content, err := m.Renderer.Render(h)
	if err != nil {
		return err
	}
	path := filepath.Join(m.SitesAvailable, h.ServerName)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing host config %s: %w", path, err)
	}
	return nil
}

// DeleteHost removes a host's sites-available file and, if present, its
// sites-enabled symlink. It does not create a backup; callers should do so
// beforehand via internal/backup.
func (m *Manager) DeleteHost(fileName string) error {
	_ = m.Disable(fileName)
	path := filepath.Join(m.SitesAvailable, fileName)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("deleting host %s: %w", fileName, err)
	}
	return nil
}

// IsEnabled reports whether fileName has an entry in SitesEnabled.
func (m *Manager) IsEnabled(fileName string) bool {
	_, err := os.Lstat(filepath.Join(m.SitesEnabled, fileName))
	return err == nil
}

// Enable creates a symlink from sites-enabled/fileName to the corresponding
// sites-available file. It is a no-op if already enabled.
func (m *Manager) Enable(fileName string) error {
	available := filepath.Join(m.SitesAvailable, fileName)
	if _, err := os.Stat(available); err != nil {
		return fmt.Errorf("host %s does not exist in sites-available: %w", fileName, err)
	}
	link := filepath.Join(m.SitesEnabled, fileName)
	if _, err := os.Lstat(link); err == nil {
		return nil // already enabled (or at least something exists there)
	}
	if err := os.Symlink(available, link); err != nil {
		return fmt.Errorf("enabling host %s: %w", fileName, err)
	}
	return nil
}

// Disable removes only the sites-enabled symlink for fileName. The
// sites-available configuration file is never touched.
func (m *Manager) Disable(fileName string) error {
	link := filepath.Join(m.SitesEnabled, fileName)
	if err := os.Remove(link); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("disabling host %s: %w", fileName, err)
	}
	return nil
}
