// Package nginx contains the domain model, configuration renderer, filesystem
// operations and validator used to manage Nginx virtual hosts.
package nginx

import "fmt"

// HostMode describes the high level purpose of a virtual host.
type HostMode string

const (
	ModeReverseProxy HostMode = "reverse_proxy"
	ModeStatic       HostMode = "static"
)

// KeyType identifies the private key algorithm used by a certificate.
type KeyType string

const (
	KeyTypeUnknown KeyType = "unknown"
	KeyTypeRSA     KeyType = "rsa"
	KeyTypeECDSA   KeyType = "ecdsa"
)

// SSLConfig holds the TLS settings applied to a host.
type SSLConfig struct {
	Enabled    bool
	CertFile   string
	KeyFile    string
	KeyType    KeyType
	HTTP2      bool
	ForceHTTPS bool // redirect plain HTTP requests to HTTPS
}

// ProxyConfig groups the reverse proxy specific settings of a location.
type ProxyConfig struct {
	UpstreamScheme   string // "http" or "https"
	UpstreamHost     string
	UpstreamPort     int
	HTTPVersion      string // "1.0", "1.1"
	ConnectTimeout   string // e.g. "60s"
	ReadTimeout      string
	SendTimeout      string
	WebSocket        bool
	ForwardHost      bool
	ForwardFor       bool
	ForwardProto     bool
	MaxBodySize      string // client_max_body_size, e.g. "10m"
	BufferingEnabled bool
}

// UpstreamURL renders the proxy_pass target, e.g. http://127.0.0.1:8080.
func (p ProxyConfig) UpstreamURL() string {
	return fmt.Sprintf("%s://%s:%d", p.UpstreamScheme, p.UpstreamHost, p.UpstreamPort)
}

// Location represents a single `location` block inside a server block.
type Location struct {
	Path           string
	IsCustom       bool   // true when CustomConfig should be used verbatim
	CustomConfig   string // raw user supplied configuration for the location
	Proxy          *ProxyConfig
	AccessListName string // empty when no access list is applied
}

// Host is the internal representation of a single Nginx virtual host,
// independent of how it is ultimately rendered to disk.
type Host struct {
	ServerName     string // primary domain, also used as the config file name
	ServerAlias    []string
	Mode           HostMode
	Listen         int    // plain HTTP port, normally 80
	ListenSSL      int    // HTTPS port, normally 443
	Root           string // used when Mode == ModeStatic
	SSL            SSLConfig
	Locations      []Location
	AccessLog      bool
	ErrorLog       bool
	AccessListName string // access list applied at server level, empty if none

	// Managed is false when the configuration file was not generated by
	// nginx-manager (e.g. hand written). Such hosts are shown read-only
	// unless the user explicitly opts into management.
	Managed bool

	// Enabled reflects whether a symlink exists in sites-enabled. This is
	// computed at discovery time, not stored in the config file.
	Enabled bool
}

// Validate performs basic structural validation of the host model before it
// is rendered to an Nginx configuration file. It does not invoke `nginx -t`;
// that is the job of the Validator.
func (h Host) Validate() error {
	if h.ServerName == "" {
		return fmt.Errorf("server name must not be empty")
	}
	if h.Mode == ModeReverseProxy && len(h.Locations) == 0 {
		return fmt.Errorf("reverse proxy host %q must have at least one location", h.ServerName)
	}
	if h.Mode == ModeStatic && h.Root == "" {
		return fmt.Errorf("static host %q must have a root directory", h.ServerName)
	}
	for _, loc := range h.Locations {
		if loc.Path == "" {
			return fmt.Errorf("location in host %q has an empty path", h.ServerName)
		}
		if !loc.IsCustom && loc.Proxy == nil {
			return fmt.Errorf("location %q in host %q is not custom but has no proxy configuration", loc.Path, h.ServerName)
		}
	}
	if h.SSL.Enabled {
		if h.SSL.CertFile == "" || h.SSL.KeyFile == "" {
			return fmt.Errorf("host %q has SSL enabled but is missing certificate paths", h.ServerName)
		}
	}
	return nil
}
