package nginx

import (
	"regexp"
	"strconv"
	"strings"
)

// ManagedMarker is written as a comment at the top of every configuration
// file generated by GoNix, so it can later recognize its own files
// versus hand-written ones.
const ManagedMarker = "# Managed by GoNix."

var (
	reServerName    = regexp.MustCompile(`(?m)^\s*server_name\s+([^;]+);`)
	reListen        = regexp.MustCompile(`(?m)^\s*listen\s+(\d+)([^;]*);`)
	reSSLCert       = regexp.MustCompile(`(?m)^\s*ssl_certificate\s+([^;]+);`)
	reSSLKey        = regexp.MustCompile(`(?m)^\s*ssl_certificate_key\s+([^;]+);`)
	reRoot          = regexp.MustCompile(`(?m)^\s*root\s+([^;]+);`)
	reAccessLog     = regexp.MustCompile(`(?m)^\s*access_log\s+([^;]+);`)
	reErrorLog      = regexp.MustCompile(`(?m)^\s*error_log\s+([^;]+);`)
	reAuthUserFile  = regexp.MustCompile(`(?m)^\s*auth_basic_user_file\s+([^;]+);`)
	reLocationStart = regexp.MustCompile(`^\s*location\s+(\S+)\s*\{`)
	reProxyPass     = regexp.MustCompile(`(?m)^\s*proxy_pass\s+([^;]+);`)
	reProxyHTTPVer  = regexp.MustCompile(`(?m)^\s*proxy_http_version\s+([^;]+);`)
	reProxyConnTO   = regexp.MustCompile(`(?m)^\s*proxy_connect_timeout\s+([^;]+);`)
	reProxyReadTO   = regexp.MustCompile(`(?m)^\s*proxy_read_timeout\s+([^;]+);`)
	reProxySendTO   = regexp.MustCompile(`(?m)^\s*proxy_send_timeout\s+([^;]+);`)
	reMaxBodySize   = regexp.MustCompile(`(?m)^\s*client_max_body_size\s+([^;]+);`)
)

// Summary is a lightweight, best-effort extraction of information from an
// arbitrary Nginx server configuration file. It is used to display hosts
// that were not generated by GoNix without attempting a full,
// potentially unsafe, parse/rewrite cycle.
type Summary struct {
	ServerNames []string
	ListenPorts []int
	SSL         bool
	Managed     bool
}

// ParseSummary extracts a best-effort summary from raw Nginx configuration
// content. It never errors: unparsable input simply yields a mostly-empty
// summary, since the file is treated as opaque/custom in that case.
func ParseSummary(content string) Summary {
	s := Summary{Managed: strings.Contains(content, ManagedMarker)}

	if m := reServerName.FindStringSubmatch(content); m != nil {
		s.ServerNames = strings.Fields(m[1])
	}
	for _, m := range reListen.FindAllStringSubmatch(content, -1) {
		if port, err := strconv.Atoi(m[1]); err == nil {
			s.ListenPorts = append(s.ListenPorts, port)
		}
		if strings.Contains(m[2], "ssl") {
			s.SSL = true
		}
	}
	return s
}

// ParseManagedHost reconstructs a Host from configuration content that was
// previously generated by this application's Renderer. It relies on the
// predictable structure produced by the templates and is not intended to
// parse arbitrary hand-written Nginx configuration.
func ParseManagedHost(content string) (Host, error) {
	h := Host{Managed: true, AccessLog: true, ErrorLog: true, Mode: ModeReverseProxy}

	if m := reServerName.FindStringSubmatch(content); m != nil {
		names := strings.Fields(m[1])
		if len(names) > 0 {
			h.ServerName = names[0]
			h.ServerAlias = names[1:]
		}
	}
	for _, m := range reListen.FindAllStringSubmatch(content, -1) {
		port, _ := strconv.Atoi(m[1])
		if strings.Contains(m[2], "ssl") {
			h.ListenSSL = port
			h.SSL.Enabled = true
			h.SSL.HTTP2 = strings.Contains(m[2], "http2")
		} else {
			h.Listen = port
		}
	}
	if m := reSSLCert.FindStringSubmatch(content); m != nil {
		h.SSL.CertFile = strings.TrimSpace(m[1])
	}
	if m := reSSLKey.FindStringSubmatch(content); m != nil {
		h.SSL.KeyFile = strings.TrimSpace(m[1])
	}
	h.SSL.ForceHTTPS = strings.Contains(content, `if ($scheme != "https")`)

	if m := reRoot.FindStringSubmatch(content); m != nil {
		h.Root = strings.TrimSpace(m[1])
		h.Mode = ModeStatic
	}

	if m := reAccessLog.FindStringSubmatch(content); m != nil {
		h.AccessLog = strings.TrimSpace(m[1]) != "off"
	} else if strings.Contains(content, "access_log off;") {
		h.AccessLog = false
	}
	if m := reErrorLog.FindStringSubmatch(content); m != nil {
		h.ErrorLog = strings.TrimSpace(m[1]) != "off"
	} else if strings.Contains(content, "error_log off;") {
		h.ErrorLog = false
	}

	// Host-level auth_basic_user_file appears before the first location
	// block; anything after belongs to a location.
	if idx := reLocationStart.FindStringIndex(content); idx == nil {
		if m := reAuthUserFile.FindStringSubmatch(content); m != nil {
			h.AccessListName = accessListNameFromPath(m[1])
		}
	} else if m := reAuthUserFile.FindStringSubmatch(content[:idx[0]]); m != nil {
		h.AccessListName = accessListNameFromPath(m[1])
	}

	h.Locations = parseLocations(content)
	return h, nil
}

func accessListNameFromPath(p string) string {
	p = strings.TrimSpace(p)
	base := p
	if i := strings.LastIndexByte(p, '/'); i >= 0 {
		base = p[i+1:]
	}
	return strings.TrimSuffix(base, ".htpasswd")
}

// parseLocations splits the server block body into individual `location`
// blocks by tracking brace depth, then extracts known reverse-proxy
// directives from each one.
func parseLocations(content string) []Location {
	var locations []Location
	lines := strings.Split(content, "\n")

	for i := 0; i < len(lines); i++ {
		m := reLocationStart.FindStringSubmatch(lines[i])
		if m == nil {
			continue
		}
		path := m[1]
		depth := 1
		start := i + 1
		end := start
		for j := start; j < len(lines) && depth > 0; j++ {
			depth += strings.Count(lines[j], "{")
			depth -= strings.Count(lines[j], "}")
			end = j
		}
		body := strings.Join(lines[start:end], "\n")
		locations = append(locations, parseLocationBody(path, body))
		i = end
	}
	return locations
}

func parseLocationBody(path, body string) Location {
	loc := Location{Path: path}

	if strings.Contains(body, "# User-defined configuration") {
		loc.IsCustom = true
		loc.CustomConfig = body
		return loc
	}

	pp := ProxyConfig{HTTPVersion: "1.1"}
	if m := reProxyPass.FindStringSubmatch(body); m != nil {
		parseUpstreamURL(strings.TrimSpace(m[1]), &pp)
	}
	if m := reProxyHTTPVer.FindStringSubmatch(body); m != nil {
		pp.HTTPVersion = strings.Trim(strings.TrimSpace(m[1]), `"`)
	}
	pp.ForwardHost = strings.Contains(body, "proxy_set_header Host $host;")
	pp.ForwardFor = strings.Contains(body, "X-Forwarded-For")
	pp.ForwardProto = strings.Contains(body, "X-Forwarded-Proto")
	pp.WebSocket = strings.Contains(body, "Upgrade $http_upgrade")
	pp.BufferingEnabled = !strings.Contains(body, "proxy_buffering off;")
	if m := reProxyConnTO.FindStringSubmatch(body); m != nil {
		pp.ConnectTimeout = strings.TrimSpace(m[1])
	}
	if m := reProxyReadTO.FindStringSubmatch(body); m != nil {
		pp.ReadTimeout = strings.TrimSpace(m[1])
	}
	if m := reProxySendTO.FindStringSubmatch(body); m != nil {
		pp.SendTimeout = strings.TrimSpace(m[1])
	}
	if m := reMaxBodySize.FindStringSubmatch(body); m != nil {
		pp.MaxBodySize = strings.TrimSpace(m[1])
	}
	loc.Proxy = &pp

	if m := reAuthUserFile.FindStringSubmatch(body); m != nil {
		loc.AccessListName = accessListNameFromPath(m[1])
	}
	return loc
}

func parseUpstreamURL(u string, pp *ProxyConfig) {
	scheme := "http"
	rest := u
	if strings.HasPrefix(u, "https://") {
		scheme = "https"
		rest = strings.TrimPrefix(u, "https://")
	} else if strings.HasPrefix(u, "http://") {
		rest = strings.TrimPrefix(u, "http://")
	}
	pp.UpstreamScheme = scheme
	host := rest
	port := 80
	if i := strings.LastIndexByte(rest, ':'); i >= 0 {
		host = rest[:i]
		if p, err := strconv.Atoi(rest[i+1:]); err == nil {
			port = p
		}
	}
	pp.UpstreamHost = host
	pp.UpstreamPort = port
}
